[theme]
primaryColor = "#4B9CD3"                # Calm healthcare blue
backgroundColor = "#FFFFFF"             # Clean white base
secondaryBackgroundColor = "#F0F2F6"    # Light gray card background
textColor = "#000000"                   # Standard readable black
font = "sans serif" 